from uuid import UUID, uuid4
from datetime import datetime, timezone

from sqlalchemy import Boolean, CheckConstraint, DateTime, Float, ForeignKey, Integer, String, Text, Uuid
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


# Base class used by SQLAlchemy for all database models. -H
class Base(DeclarativeBase):
    pass
# Stores application users for authentication and authorization. -H
class User(Base):
    __tablename__ = "users"

    # UUID keeps user identifiers independent from sequential database IDs. -H
    id: Mapped[UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid4,
    )

    # Email is used as the unique account identifier. -H
    email: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        unique=True,
    )

    # Stores the hashed password only.
    # Plain-text passwords must never be stored in the database. -H
    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    # Application authorization role.
    # Allowed values are viewer, member, and admin. -H
    role: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="member",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Prevent invalid role values from being stored in PostgreSQL. -H
    __table_args__ = (
        CheckConstraint(
            "role IN ('viewer', 'member', 'admin')",
            name="ck_users_role",
        ),
    )

# Stores one complete benchmark experiment.
# A benchmark run represents one task tested in one language
# with a specific model and inference configuration. -H
class BenchmarkRun(Base):
    __tablename__ = "benchmark_runs"

    id: Mapped[int] = mapped_column(primary_key=True)

    # Matches the task id defined in ZakBench, such as "array_sum". -H
    task_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    # Expected values are currently "python" or "zak". -H
    language: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    # Name of the model used for this benchmark run. -H
    model_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    # Optional inference settings used for reproducibility. -H
    temperature: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    max_tokens: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    # Tracks the current state of the run.
    # Examples: pending, running, completed, failed. -H
    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="pending",
    )

    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # One benchmark run can contain multiple generation attempts. -H
    attempts: Mapped[list["Attempt"]] = relationship(
        back_populates="run",
        cascade="all, delete-orphan",
    )


# Stores each individual model generation.
# Attempt 1 is the initial generation and later attempts can be repairs. -H
class Attempt(Base):
    __tablename__ = "attempts"

    id: Mapped[int] = mapped_column(primary_key=True)

    # Connects this attempt to its parent benchmark run. -H
    run_id: Mapped[int] = mapped_column(
        ForeignKey("benchmark_runs.id"),
        nullable=False,
    )

    # 1 = original generation, 2+ = repair attempts. -H
    attempt_number: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    # Exact prompt sent to the model. -H
    prompt_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # Code generated by the model. -H
    generated_code: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # Token counts reported by the inference server. -H
    prompt_tokens: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    completion_tokens: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    total_tokens: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    finish_reason: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    # Model request latency in milliseconds. -H
    latency_ms: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    run: Mapped["BenchmarkRun"] = relationship(
        back_populates="attempts",
    )

    # Each attempt receives at most one evaluation result. -H
    evaluation: Mapped["Evaluation | None"] = relationship(
        back_populates="attempt",
        uselist=False,
        cascade="all, delete-orphan",
    )


# Stores correctness and execution results for one generated solution. -H
class Evaluation(Base):
    __tablename__ = "evaluations"

    id: Mapped[int] = mapped_column(primary_key=True)

    # One evaluation belongs to exactly one attempt. -H
    attempt_id: Mapped[int] = mapped_column(
        ForeignKey("attempts.id"),
        nullable=False,
        unique=True,
    )

    # For Zak, indicates whether compilation/transpilation succeeded.
    # Python runs may leave this null. -H
    compile_success: Mapped[bool | None] = mapped_column(
        Boolean,
        nullable=True,
    )

    # Compiler output or compiler errors used for repair prompts. -H
    compiler_output: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # Python produced by the Zak transpiler.
    # Null for normal Python benchmark runs. -H
    transpiled_code: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    tests_passed: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    tests_total: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    # True when the generated solution passes the required evaluation. -H
    correct: Mapped[bool | None] = mapped_column(
        Boolean,
        nullable=True,
    )

    # Execution and testing duration in milliseconds. -H
    execution_ms: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    attempt: Mapped["Attempt"] = relationship(
        back_populates="evaluation",
    )